// <auto-generated />
using System;
using Loopin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loopin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411113826_loopin6")]
    partial class loopin6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AboneOlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AboneOlunanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AboneOlanId");

                    b.HasIndex("AboneOlunanId");

                    b.ToTable("Abonelikler");
                });

            modelBuilder.Entity("Loopin.Models.Begenme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("Begenmeler");
                });

            modelBuilder.Entity("Loopin.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IzlenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapakResmiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Videolar");
                });

            modelBuilder.Entity("Loopin.Models.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Abonelik", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "AboneOlan")
                        .WithMany()
                        .HasForeignKey("AboneOlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Kullanici", "AboneOlunan")
                        .WithMany()
                        .HasForeignKey("AboneOlunanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboneOlan");

                    b.Navigation("AboneOlunan");
                });

            modelBuilder.Entity("Loopin.Models.Begenme", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany("VideoBegenmeler")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany("Videolar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Loopin.Models.Yorum", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany("VideoYorumlar")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.Kullanici", b =>
                {
                    b.Navigation("Videolar");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.Navigation("VideoBegenmeler");

                    b.Navigation("VideoYorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
