// <auto-generated />
using System;
using Loopin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loopin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AboneOlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AboneOlunanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AboneOlanId");

                    b.HasIndex("AboneOlunanId");

                    b.ToTable("Abonelikler");
                });

            modelBuilder.Entity("DahaSonraIzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("DahaSonraIzleListesi");
                });

            modelBuilder.Entity("Gecmis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IzlenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("GecmisListesi");
                });

            modelBuilder.Entity("Loopin.Models.Begenme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("Begenmeler");
                });

            modelBuilder.Entity("Loopin.Models.KanalEtkilesimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "Tarih", "Tur");

                    b.ToTable("KanalEtkilesimleri");
                });

            modelBuilder.Entity("Loopin.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailOnayExpire")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailOnayToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOnayli")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetCodeExpire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Loopin.Models.MobilBildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KanalKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Okundu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KanalKullaniciId");

                    b.HasIndex("VideoId");

                    b.HasIndex("KullaniciId", "Okundu", "OlusturulmaTarihi");

                    b.ToTable("MobilBildirimleri");
                });

            modelBuilder.Entity("Loopin.Models.MobilCihazToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CihazId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("KullaniciId", "Aktif");

                    b.ToTable("MobilCihazTokenlari");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AboneSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IzlenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapakResmiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Videolar");
                });

            modelBuilder.Entity("Loopin.Models.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VideoId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Abonelik", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "AboneOlan")
                        .WithMany()
                        .HasForeignKey("AboneOlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Kullanici", "AboneOlunan")
                        .WithMany()
                        .HasForeignKey("AboneOlunanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboneOlan");

                    b.Navigation("AboneOlunan");
                });

            modelBuilder.Entity("DahaSonraIzle", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Gecmis", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.Begenme", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany("VideoBegenmeler")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.KanalEtkilesimi", b =>
                {
                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.MobilBildirim", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "KanalKullanici")
                        .WithMany()
                        .HasForeignKey("KanalKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KanalKullanici");

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.MobilCihazToken", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany("Videolar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Loopin.Models.Yorum", b =>
                {
                    b.HasOne("Loopin.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loopin.Models.Video", "Video")
                        .WithMany("VideoYorumlar")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Loopin.Models.Kullanici", b =>
                {
                    b.Navigation("Videolar");
                });

            modelBuilder.Entity("Loopin.Models.Video", b =>
                {
                    b.Navigation("VideoBegenmeler");

                    b.Navigation("VideoYorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
